package com.murainy.safeexam.Utils;

/**
 * Created by ${USER} on ${DATE}.
 */
public enum Action {
    DOWNLOAD_GRADE_LIST,
    DOWNLOAD_PAPER_LIST,
    DOWNLOAD_Test_LIST,
    DOWNLOAD_QUESTION_SET,
    DOWNLOAD_QUESTION_EXAM,
    DOWNLOAD_QUESTION_TEST,
    DOWNLOAD_QUESTION_LIST100,
    DOWNLOAD_QUESTION_LISTINI,
	DOWNLOAD_QUESTION_LIST,
	QUERY_ERROR,
    SAVE_PAPER_SUCCESS,
    SAVE_PAPER_ERROR,
    QUESTION_COUNT,
    SAVE_GRADE_SUCCESS,
    SAVE_GRADE_ERROR
}
